configMapGenerator:
- name: chess-analyzer-envoy
  namespace: chess-analyzer
  files:
    - chess-analyzer-config/envoy.yaml
- name: client-envoy
  namespace: chess-analyzer
  files:
    - client-config/envoy.yaml

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yml
  - service-accounts.yml
  - client.yml
  - pod.yml
  - service.yml