---
apiVersion: v1
kind: Service
metadata:
  name: chess-analyzer
  namespace: chess-analyzer
spec:
  selector:
    app: chess-analyzer
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001